import { DigitalService, DigitalCode } from '../src/types';

export const INITIAL_DIGITAL_SERVICES: DigitalService[] = [
  {
    id: 'dig_svc_freefire',
    name: 'Free Fire Diamonds Top-Up (Garena)',
    slug: 'free-fire-diamonds',
    category: 'game_topup',
    description: 'Rechaje dyaman Free Fire dirèkteman sou kont jwè ou ak UID. Rapid, fyab epi san risk blokis. Sèvis ofisyèl Mache Yogann.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    ],
    providerName: 'Fournisseur Direct Mache Yogann / Garena Partner',
    providerProductId: 'GFF_DIAMONDS_GLOBAL',
    defaultCostPrice: 180,
    defaultSellingPrice: 250,
    currency: 'HTG',
    profit: 70,
    marginPercent: 28,
    packages: [
      {
        id: 'ff_100',
        name: '100 Diamonds (+10 Bonus)',
        costPrice: 180,
        sellingPrice: 250,
        currency: 'HTG',
        profit: 70,
        marginPercent: 28,
        badge: 'Popilè',
      },
      {
        id: 'ff_310',
        name: '310 Diamonds (+31 Bonus)',
        costPrice: 500,
        sellingPrice: 700,
        currency: 'HTG',
        profit: 200,
        marginPercent: 28.5,
      },
      {
        id: 'ff_520',
        name: '520 Diamonds (+52 Bonus)',
        costPrice: 800,
        sellingPrice: 1150,
        currency: 'HTG',
        profit: 350,
        marginPercent: 30.4,
        badge: 'Meyè Valè',
      },
      {
        id: 'ff_1060',
        name: '1,060 Diamonds (+106 Bonus)',
        costPrice: 1550,
        sellingPrice: 2200,
        currency: 'HTG',
        profit: 650,
        marginPercent: 29.5,
      },
      {
        id: 'ff_weekly',
        name: 'Weekly Membership (Abonman Semèn)',
        costPrice: 320,
        sellingPrice: 450,
        currency: 'HTG',
        profit: 130,
        marginPercent: 28.8,
      },
      {
        id: 'ff_monthly',
        name: 'Monthly Membership (Abonman Mwa)',
        costPrice: 1400,
        sellingPrice: 1950,
        currency: 'HTG',
        profit: 550,
        marginPercent: 28.2,
      },
    ],
    availableCountries: ['HT', 'DO', 'US', 'Tout'],
    availableRegions: ['Haiti / Caraïbes / NA', 'Amérique Latine', 'Global'],
    minDeliveryMinutes: 5,
    maxDeliveryMinutes: 30,
    deliveryType: 'manual_recharge',
    clientInstructions: 'Mete Player ID (UID) Free Fire ou a avèk presizyon. Ou ka kopye li dirèkteman nan pwofil jwèt ou an.',
    termsAndConditions: 'Verifye UID ou avan ou valide. Mache Yogann pa responsab si ou mete yon move UID.',
    requiredFields: [
      {
        id: 'playerId',
        label: 'Player ID (UID Free Fire)',
        type: 'number',
        placeholder: 'Egzanp: 1849204821',
        required: true,
        helpText: 'Ale nan pwofil jwèt ou, klike sou ikòn kopye a bò kote UID ou a.',
      },
      {
        id: 'serverId',
        label: 'Sèvè / Rejyon Kont lan',
        type: 'select',
        placeholder: 'Chwazi rejyon ou',
        required: true,
        options: ['Haiti / Caraïbes / NA', 'Amérique Latine', 'Global / Autre'],
      },
      {
        id: 'playerNickname',
        label: 'Ti Non nan Jwèt la (Nickname)',
        type: 'text',
        placeholder: 'Egzanp: Killer_Yogann',
        required: false,
        helpText: 'Opsyonèl, pou nou verifye si UID a matche ak non an.',
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_pubg',
    name: 'PUBG Mobile UC Top-Up',
    slug: 'pubg-mobile-uc',
    category: 'game_topup',
    description: 'Rechaje Unknown Cash (UC) pou PUBG Mobile. Debloke Royale Pass, po zam ak kès lejandè san difikilte.',
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80'],
    providerName: 'Fournisseur Direct Mache Yogann / Tencent Distributor',
    providerProductId: 'PUBGM_UC_GLOBAL',
    defaultCostPrice: 150,
    defaultSellingPrice: 220,
    currency: 'HTG',
    profit: 70,
    marginPercent: 31.8,
    packages: [
      {
        id: 'pubg_60',
        name: '60 UC',
        costPrice: 150,
        sellingPrice: 220,
        currency: 'HTG',
        profit: 70,
        marginPercent: 31.8,
      },
      {
        id: 'pubg_325',
        name: '325 UC',
        costPrice: 700,
        sellingPrice: 990,
        currency: 'HTG',
        profit: 290,
        marginPercent: 29.2,
      },
      {
        id: 'pubg_660',
        name: '660 UC (Elite Pass)',
        costPrice: 1400,
        sellingPrice: 1950,
        currency: 'HTG',
        profit: 550,
        marginPercent: 28.2,
        badge: 'Elite Pass',
      },
      {
        id: 'pubg_1800',
        name: '1,800 UC',
        costPrice: 3600,
        sellingPrice: 4950,
        currency: 'HTG',
        profit: 1350,
        marginPercent: 27.2,
      },
    ],
    availableCountries: ['HT', 'DO', 'US', 'Tout'],
    availableRegions: ['Global', 'North America'],
    minDeliveryMinutes: 10,
    maxDeliveryMinutes: 45,
    deliveryType: 'manual_recharge',
    clientInstructions: 'Antre Character ID (ID nimerik) PUBG ou an.',
    requiredFields: [
      {
        id: 'playerId',
        label: 'Character ID (PUBG UID)',
        type: 'number',
        placeholder: 'Egzanp: 5192837410',
        required: true,
        helpText: 'Ou jwenn ID nimerik sa a sou pwofil PUBG Mobile ou.',
      },
      {
        id: 'playerName',
        label: 'Non Jwè PUBG (In-Game Name)',
        type: 'text',
        placeholder: 'Egzanp: GhostRider509',
        required: false,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-09-11T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_roblox',
    name: 'Roblox Robux Direct Recharge',
    slug: 'roblox-robux-direct',
    category: 'game_topup',
    description: 'Robux ofisyèl pou tout jwè Roblox nan Leyogàn ak Ayiti. Achte rad, pas jwèt ak atik eksklizif.',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    providerName: 'Mache Yogann Roblox Distribution',
    defaultCostPrice: 750,
    defaultSellingPrice: 1050,
    currency: 'HTG',
    profit: 300,
    marginPercent: 28.5,
    packages: [
      {
        id: 'rbx_400',
        name: '400 Robux',
        costPrice: 750,
        sellingPrice: 1050,
        currency: 'HTG',
        profit: 300,
        marginPercent: 28.5,
      },
      {
        id: 'rbx_800',
        name: '800 Robux',
        costPrice: 1450,
        sellingPrice: 2050,
        currency: 'HTG',
        profit: 600,
        marginPercent: 29.2,
        badge: 'Popilè',
      },
      {
        id: 'rbx_1700',
        name: '1,700 Robux',
        costPrice: 3000,
        sellingPrice: 4200,
        currency: 'HTG',
        profit: 1200,
        marginPercent: 28.5,
      },
    ],
    availableCountries: ['HT', 'Tout'],
    availableRegions: ['Global'],
    minDeliveryMinutes: 10,
    maxDeliveryMinutes: 40,
    deliveryType: 'manual_recharge',
    clientInstructions: 'Mete non itilizatè Roblox egzat ou.',
    requiredFields: [
      {
        id: 'robloxUsername',
        label: 'Roblox Username (Non Itilizatè)',
        type: 'text',
        placeholder: 'Egzanp: HaitiGamer2026',
        required: true,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_steam',
    name: 'Steam Gift Card (Kòd Kat Kado Global)',
    slug: 'steam-gift-card-global',
    category: 'gift_card',
    description: 'Kat kado Steam pou achte jwèt sou PC. Ou resevwa kòd voucher dijital la dirèkteman sou paj kòmand ou an apre verifikasyon.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    providerName: 'Distributeur Valve Steam Agréé',
    defaultCostPrice: 700,
    defaultSellingPrice: 950,
    currency: 'HTG',
    profit: 250,
    marginPercent: 26.3,
    packages: [
      {
        id: 'steam_5usd',
        name: 'Steam Card $5 USD',
        costPrice: 700,
        sellingPrice: 950,
        currency: 'HTG',
        profit: 250,
        marginPercent: 26.3,
      },
      {
        id: 'steam_10usd',
        name: 'Steam Card $10 USD',
        costPrice: 1350,
        sellingPrice: 1800,
        currency: 'HTG',
        profit: 450,
        marginPercent: 25,
        badge: 'Pi Mande',
      },
      {
        id: 'steam_20usd',
        name: 'Steam Card $20 USD',
        costPrice: 2650,
        sellingPrice: 3500,
        currency: 'HTG',
        profit: 850,
        marginPercent: 24.2,
      },
      {
        id: 'steam_50usd',
        name: 'Steam Card $50 USD',
        costPrice: 6600,
        sellingPrice: 8600,
        currency: 'HTG',
        profit: 2000,
        marginPercent: 23.2,
      },
    ],
    availableCountries: ['Tout'],
    availableRegions: ['Global / Tout Rejyon'],
    minDeliveryMinutes: 5,
    maxDeliveryMinutes: 20,
    deliveryType: 'instant_code',
    clientInstructions: 'Apre livrezon, kopye kòd la epi itilize li sou store.steampowered.com/account/redeemwalletcode.',
    requiredFields: [
      {
        id: 'accountRegion',
        label: 'Rejyon Kont Steam Ou',
        type: 'select',
        placeholder: 'Chwazi rejyon',
        required: true,
        options: ['Global / Tout Rejyon', 'USA ($ USD)', 'Amérique Latine'],
      },
      {
        id: 'deliveryEmail',
        label: 'Imèl oswa WhatsApp pou Resevwa Kòd la',
        type: 'text',
        placeholder: 'Egzanp: ou@gmail.com oswa +509 37...',
        required: true,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_googleplay',
    name: 'Google Play Gift Card (US & Global)',
    slug: 'google-play-gift-card',
    category: 'gift_card',
    description: 'Kat kado Google Play pou achte aplikasyon, liv, fim, ak tranzaksyon anndan jwèt Android yo.',
    image: 'https://images.unsplash.com/photo-1556742049-0a67e5572293?auto=format&fit=crop&w=800&q=80',
    providerName: 'Fournisseur Agréé Google Play',
    defaultCostPrice: 700,
    defaultSellingPrice: 950,
    currency: 'HTG',
    profit: 250,
    marginPercent: 26.3,
    packages: [
      {
        id: 'gp_5usd',
        name: 'Google Play $5 USD',
        costPrice: 700,
        sellingPrice: 950,
        currency: 'HTG',
        profit: 250,
        marginPercent: 26.3,
      },
      {
        id: 'gp_10usd',
        name: 'Google Play $10 USD',
        costPrice: 1350,
        sellingPrice: 1800,
        currency: 'HTG',
        profit: 450,
        marginPercent: 25,
        badge: 'Top Vant',
      },
      {
        id: 'gp_25usd',
        name: 'Google Play $25 USD',
        costPrice: 3300,
        sellingPrice: 4400,
        currency: 'HTG',
        profit: 1100,
        marginPercent: 25,
      },
    ],
    availableCountries: ['Tout'],
    availableRegions: ['USA Store', 'Global'],
    minDeliveryMinutes: 5,
    maxDeliveryMinutes: 20,
    deliveryType: 'instant_code',
    clientInstructions: 'Kòd la dwe aktive sou yon kont Google Play ki konfigire sou rejyon Etazini oswa rejyon ki koresponn lan.',
    requiredFields: [
      {
        id: 'storeCountry',
        label: 'Rejyon Kont Google Play ou',
        type: 'select',
        placeholder: 'Chwazi',
        required: true,
        options: ['USA (US Play Store)', 'Global / Autre'],
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-09-09T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_apple',
    name: 'Apple & App Store Gift Card',
    slug: 'apple-gift-card',
    category: 'gift_card',
    description: 'Kat kado ofisyèl Apple pou iPhone, iPad ak Mac. Pou peye iCloud, Apple Music, jwèt ak abònman.',
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    providerName: 'Partenaire Distributeur Apple',
    defaultCostPrice: 1350,
    defaultSellingPrice: 1850,
    currency: 'HTG',
    profit: 500,
    marginPercent: 27,
    packages: [
      {
        id: 'apple_10usd',
        name: 'Apple Card $10 USD',
        costPrice: 1350,
        sellingPrice: 1850,
        currency: 'HTG',
        profit: 500,
        marginPercent: 27,
      },
      {
        id: 'apple_25usd',
        name: 'Apple Card $25 USD',
        costPrice: 3300,
        sellingPrice: 4450,
        currency: 'HTG',
        profit: 1150,
        marginPercent: 25.8,
      },
    ],
    availableCountries: ['Tout'],
    availableRegions: ['USA App Store'],
    minDeliveryMinutes: 5,
    maxDeliveryMinutes: 20,
    deliveryType: 'instant_code',
    clientInstructions: 'Kòd sa a itilize sou App Store nan seksyon "Redeem Gift Card".',
    requiredFields: [
      {
        id: 'appleRegion',
        label: 'Rejyon Apple ID',
        type: 'select',
        placeholder: 'Chwazi',
        required: true,
        options: ['US App Store (Etazini)', 'Autre'],
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-09-09T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_digicel',
    name: 'Digicel Haiti - Recharge & Plan Entènèt',
    slug: 'digicel-haiti-recharge',
    category: 'mobile_topup',
    description: 'Voye recharge ak plan entènèt dirèkteman sou nenpòt nimewo Digicel an Ayiti (Léogâne ak tout peyi a). Tretman rapid pa Mache Yogann.',
    image: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=800&q=80',
    providerName: 'Recharge Direct Télécom Haiti / Digicel',
    defaultCostPrice: 240,
    defaultSellingPrice: 275,
    currency: 'HTG',
    profit: 35,
    marginPercent: 12.7,
    packages: [
      {
        id: 'digi_250',
        name: '250 HTG Recharge Kredi',
        costPrice: 240,
        sellingPrice: 275,
        currency: 'HTG',
        profit: 35,
        marginPercent: 12.7,
      },
      {
        id: 'digi_500',
        name: '500 HTG Recharge Kredi',
        costPrice: 480,
        sellingPrice: 550,
        currency: 'HTG',
        profit: 70,
        marginPercent: 12.7,
        badge: 'Popilè',
      },
      {
        id: 'digi_1000',
        name: '1,000 HTG Recharge Kredi',
        costPrice: 960,
        sellingPrice: 1100,
        currency: 'HTG',
        profit: 140,
        marginPercent: 12.7,
      },
      {
        id: 'digi_data_6gb',
        name: 'Plan Entènèt 15 Jou - 6GB Data',
        costPrice: 550,
        sellingPrice: 650,
        currency: 'HTG',
        profit: 100,
        marginPercent: 15.4,
        badge: 'Pake Data',
      },
    ],
    availableCountries: ['HT'],
    availableRegions: ['Haiti'],
    minDeliveryMinutes: 3,
    maxDeliveryMinutes: 15,
    deliveryType: 'manual_recharge',
    clientInstructions: 'Mete nimewo telefòn Digicel 8 chif ou an (san 509 oswa avèk 509).',
    requiredFields: [
      {
        id: 'phoneNumber',
        label: 'Nimewo Telefòn Digicel',
        type: 'tel',
        placeholder: 'Egzanp: 37123456 oswa +509 37123456',
        required: true,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_natcom',
    name: 'Natcom Haiti - Recharge & Pake 4G LTE',
    slug: 'natcom-haiti-recharge',
    category: 'mobile_topup',
    description: 'Rechaje nenpòt nimewo Natcom an Ayiti. Kredi apèl ak plan entènèt 4G gwo vitès san deplase.',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    providerName: 'Recharge Direct Télécom Haiti / Natcom',
    defaultCostPrice: 190,
    defaultSellingPrice: 225,
    currency: 'HTG',
    profit: 35,
    marginPercent: 15.5,
    packages: [
      {
        id: 'nat_200',
        name: '200 HTG Recharge Natcom',
        costPrice: 190,
        sellingPrice: 225,
        currency: 'HTG',
        profit: 35,
        marginPercent: 15.5,
      },
      {
        id: 'nat_500',
        name: '500 HTG Recharge Natcom',
        costPrice: 475,
        sellingPrice: 550,
        currency: 'HTG',
        profit: 75,
        marginPercent: 13.6,
      },
      {
        id: 'nat_1000',
        name: '1,000 HTG Recharge Natcom',
        costPrice: 950,
        sellingPrice: 1100,
        currency: 'HTG',
        profit: 150,
        marginPercent: 13.6,
      },
      {
        id: 'nat_data_10gb',
        name: 'Pake Entènèt 4G LTE - 10GB Data',
        costPrice: 650,
        sellingPrice: 750,
        currency: 'HTG',
        profit: 100,
        marginPercent: 13.3,
        badge: 'Gwo Data',
      },
    ],
    availableCountries: ['HT'],
    availableRegions: ['Haiti'],
    minDeliveryMinutes: 3,
    maxDeliveryMinutes: 15,
    deliveryType: 'manual_recharge',
    clientInstructions: 'Mete nimewo telefòn Natcom 8 chif ou an (egzanp: 31002233).',
    requiredFields: [
      {
        id: 'phoneNumber',
        label: 'Nimewo Telefòn Natcom',
        type: 'tel',
        placeholder: 'Egzanp: 31002233 oswa +509 31002233',
        required: true,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'dig_svc_virtualcard',
    name: 'Kat Visa / Mastercard Virtiyèl (Prepaid USD)',
    slug: 'kat-visa-mastercard-vitiyel',
    category: 'virtual_card',
    description: 'Kat peman entènasyonal virtiyèl pou peye sou entènèt (Netflix, Spotify, Facebook Ads, Shein, Amazon, kou sou entènèt). Pwoteje kont prensipal ou.',
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    providerName: 'Émetteur Agréé Visa/Mastercard Fintech',
    defaultCostPrice: 1450,
    defaultSellingPrice: 1950,
    currency: 'HTG',
    profit: 500,
    marginPercent: 25.6,
    packages: [
      {
        id: 'vc_10usd',
        name: 'Kat Virtiyèl $10 USD (Prepaid)',
        costPrice: 1450,
        sellingPrice: 1950,
        currency: 'HTG',
        profit: 500,
        marginPercent: 25.6,
      },
      {
        id: 'vc_25usd',
        name: 'Kat Virtiyèl $25 USD (Prepaid)',
        costPrice: 3550,
        sellingPrice: 4750,
        currency: 'HTG',
        profit: 1200,
        marginPercent: 25.3,
        badge: 'Rekòmande',
      },
      {
        id: 'vc_50usd',
        name: 'Kat Virtiyèl $50 USD (Prepaid)',
        costPrice: 6900,
        sellingPrice: 9200,
        currency: 'HTG',
        profit: 2300,
        marginPercent: 25,
      },
    ],
    availableCountries: ['HT', 'Tout'],
    availableRegions: ['International'],
    minDeliveryMinutes: 15,
    maxDeliveryMinutes: 60,
    deliveryType: 'instant_code',
    clientInstructions: 'Done kat la (Nimewo 16 chif, Dat Ekspirasyon, CVV) ap remèt an tout sekirite nan detay kòmand ou ak sou WhatsApp.',
    termsAndConditions: 'Kat sa a se yon kat prépayée. Li fonksyone sou tout sit ki aksepte kat entènasyonal.',
    requiredFields: [
      {
        id: 'cardHolderName',
        label: 'Non Titilè Kat la (Tout Majiskil)',
        type: 'text',
        placeholder: 'Egzanp: JEAN BAPTISTE',
        required: true,
      },
      {
        id: 'whatsappNumber',
        label: 'Nimewo WhatsApp pou Konfimasyon Sekirize',
        type: 'tel',
        placeholder: 'Egzanp: +509 47 70 38 14',
        required: true,
      },
    ],
    isActive: true,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-09-06T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
];

export const INITIAL_DIGITAL_CODES: DigitalCode[] = [
  {
    id: 'code_steam_1',
    serviceId: 'dig_svc_steam',
    packageId: 'steam_10usd',
    code: 'STM-9472-KY82-9014',
    status: 'AVAILABLE',
    createdAt: '2026-09-15T10:00:00Z',
    notes: 'Lot 2026-09 #1 Valve Global',
  },
  {
    id: 'code_steam_2',
    serviceId: 'dig_svc_steam',
    packageId: 'steam_10usd',
    code: 'STM-2281-MA94-5512',
    status: 'AVAILABLE',
    createdAt: '2026-09-15T10:00:00Z',
    notes: 'Lot 2026-09 #2 Valve Global',
  },
  {
    id: 'code_gp_1',
    serviceId: 'dig_svc_googleplay',
    packageId: 'gp_10usd',
    code: 'GPLY-8841-9920-ABCD',
    status: 'AVAILABLE',
    createdAt: '2026-09-15T10:00:00Z',
    notes: 'Google Play $10 US',
  },
  {
    id: 'code_apple_1',
    serviceId: 'dig_svc_apple',
    packageId: 'apple_10usd',
    code: 'X942-APPL-7712-4401',
    status: 'AVAILABLE',
    createdAt: '2026-09-15T10:00:00Z',
    notes: 'Apple $10 US',
  },
];
